apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  labels:
    app: Food-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Food-app
  template:
    metadata:
      labels:
        app: Food-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: food
        image: mebura/foodapp:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
